export const frases: string[] = ["Não vale a pena sair do seu próprio caminho, só para fazer com que alguém goste de você. — Ash Ketchum", 
"As circunstâncias do nascimento de alguém são irrelevantes; é o que você faz com o dom da vida que determina quem você é. — Mewtwo",
"Nós temos muita coisa em comum, a mesma terra, o mesmo ar, o mesmo céu. Talvez se começássemos a olhar para as coisas que temos em comum ao invés de diferente… Bom, quem sabe? — Mewtwo",
"Você diz que tem um sonho… Esse sonho… Você tem de torná-lo realidade. Torne o seu sonho maravilhoso em realidade e ele se tornará a sua verdade. Se alguém pode fazer isso, é você! — N",
"Mesmo que não nos percebamos uns aos outros, isso não é motivo para nos rejeitarmos. Há dois lados em cada discussão. Haverá um ponto de vista que tem todas as respostas? Pense nisso! — Alder",
"Nós podemos ser malvados e ruins, mas nunca viramos as costas a um colega de equipe numa encrenca. — Jessie",
"Há maneiras más de ganhar - e há boas maneiras de perder. O que é mais interessante e problemático é que nem sempre é claro distinguir qual é qual. — Grimsley",
"O mais importante não é quanto tempo você vive. É o que você alcança com a sua vida. Enquanto eu viver eu quero brilhar. Quero provar que eu existo. Se eu pudesse, faria alguma coisa verdadeiramente importante, que definitivamente ficaria para o futuro. E assim, se eu desaparecer, eu acredito que tudo que eu consegui iria permanecer. É isso que significa viver, não é mesmo? — Grovyle",
"Você não sabe que o amor é a coisa mais importante do mundo? — Misty",
"Uma Caterpie pode evoluir para uma Butterfree, mas o coração que bate dentro dela permanece o mesmo. — Brock",
"Não há nada mais bonito e aterrorizante que a inocência. — Concordia",
"Se eu quisesse a sua opinião, eu teria pedido por ela. — Misty",
"Pokémon forte, Pokémon fraco. Essa é apenas uma percepção egoísta das pessoas. Treinadores verdadeiramente qualificados devem tentar ganhar com os seus favoritos. — Karen",
"Você sempre precisa de um motivo para ajudar alguém? — Ash Ketchum",
"É mais importante dominar as cartas que você está segurando do que reclamar sobre as que o seu adversário recebeu. — Grismley"]