export const dict = {
  "normal": "Normal",
  "fighting": "Lutador",
  "flying": "Voador",
  "poison": "Veneno",
  "ground": "Terreno",
  "rock": "Pedra",
  "bug": "Inseto",
  "ghost": "Fantasma",
  "steel": "Aço",
  "fire": "Fogo",
  "water": "Água",
  "grass": "Grama",
  "electric": "Elétrico",
  "psychic": "Psíquico",
  "ice": "Gelo",
  "dragon": "Dragão",
  "dark": "Sombrio",
  "fairy": "Fada",
  "unknown": "Desconhecido",
  "shadow": "Anti-Shiny"
};